language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Laba10_11
  - make -j
  - cd ./bin/
  - ./bin/test_polish
notifications:
  email: false
